# Generated by Django 2.2 on 2020-12-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('address', models.CharField(max_length=200)),
                ('type_of_food', models.CharField(max_length=200)),
                ('affordability', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('dine_in', models.CharField(max_length=50)),
                ('take_out', models.CharField(max_length=50)),
                ('google_maps_code', models.CharField(max_length=500)),
                ('image', models.ImageField(default='images/none/noimg.jpg', upload_to='images')),
            ],
        ),
    ]
